---
- name: "Instalando pacotes Mysql Server"
  ansible.builtin.apt:
    pkg:
      - python3-pymysql
      - mysql-server
    state: latest
    update_cache: true
    cache_valid_time: 43200 # 12 horas, nao roda o apt update (update_cache) se a lista de pacotes estiver atualizada dentro deste tempo
  become: true

- name: "Certificar que o MySQL está rodando"
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
  become: true

- name: "Criando o database wordpress no mysql"
  community.mysql.mysql_db:
    name: '{{ database }}'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
  become: true

- name: "Criando o usuário wordpress no mysql"
  community.mysql.mysql_user:
    name: '{{ username }}'
    password: '{{ password }}'
    host: localhost
    priv: '{{ database }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
    host: '{{ item }}'
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - "{{ hostvars['wordpress-server'].ansible_host }}" # pegando o ip da instancia wordpress definida no hosts.ini
  become: true

# /etc/mysql/mysql.conf.d
- name: "Replace no endereco de acesso ao mysql, liberando para qualquer ip"
  ansible.builtin.replace:
    path: '/etc/mysql/mysql.conf.d/mysqld.cnf'
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  notify: 
    - restart mysql
  become: true