---
# Comando para rodar: ansible-playbook provisioning.yml -i hosts.ini

- hosts: wordpress
  roles:
  #  - apache Nao é necessario aqui, pois esta definido que wordpress é dependente do apache na "meta"
    - wordpress

- hosts: mysql
  roles:
    - mysql